name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_adder:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        package:
          - adder
          - branches
          - collections
          - enums
          - fuckrenheit
          - functions
          - generics
          - gg
          - hash
          - hello_cargo
          - lifetimes
          - loops
          - minigrep
          - ownership
          - panic
          - reference
          - restaurant
          - string
          - structs
          - variables
          - pig_latin

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd ${{ matrix.package }} && cargo build --verbose
    - name: Run tests
      run: cd ${{ matrix.package }} && cargo test --verbose
